- hosts: all
  remote_user: vagrant
  tasks:
      - name: clone errbit repository
        git: repo=http://github.com/errbit/errbit dest=/home/vagrant/errbit/

      - name: bundle install
        bundler: state=present gemfile=/home/vagrant/errbit/Gemfile
