- hosts: all
  remote_user: vagrant
  tasks:
      - name: clone errbit repository
        git: repo=http://github.com/errbit/errbit dest=/home/vagrant/errbit/

      - name: install gem dependencies
        shell: bundle install chdir=/home/vagrant/errbit/
