- hosts: vm_web
  remote_user: vagrant

  tasks:

     - name: install bundle
       sudo: yes
       command: 'gem install bundler'

     - name: install gem dependencies
       command: 'bundle install'
       args:
         chdir: /home/vagrant/errbit

     - name: get database ip
       lineinfile:
         dest: /home/vagrant/errbit/.env.default
         regexp: ^MONGO_URL
         line: "MONGO_URL=mongodb://{{ hostvars['vm_db']['ansible_eth1']['ipv4']['address'] }}"

     - name: bootstrap errbit
       command: 'bundle exec rake errbit:bootstrap'
       args:
         chdir: /home/vagrant/errbit

     - name: start Rails server
       command: 'bundle exec rails server'
       args:
         chdir: /home/vagrant/errbit

     - name: copy nginx config
       copy:
         src: config/default
         dest: /etc/nginx/sites-available/default
         mode: 0644
         user: root
         group: root

     - name: restart nginx
       service:
          name: nginx
          state: restarted
