- hosts: all
  remote_user: vagrant

  tasks:

      - name: clone errbit repository
        sudo: yes
        git: repo=http://github.com/errbit/errbit dest=/home/vagrant/errbit/

      - name: install bundle
        sudo: yes
        command: 'gem install bundler'

      - name: install gem dependencies
        command: 'bundle install'
        args:
            chdir: /home/vagrant/errbit/

# http://stackoverflow.com/questions/32025776/how-to-get-ip-address-from-other-host-in-ansible
